TRAIN:
  ENABLE: True
  DATASET: ava
  BATCH_SIZE: 8
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_INFLATE: False
  CHECKPOINT_FILE_PATH: "path/to/pretrain.pth"
  CHECKPOINT_TYPE: pytorch
  CHECKPOINT_CLEAR_NAME_PATTERN: ("backbone.","encoder.")
DATA:
  PATH_TO_DATA_DIR: "path/to/ava"
  NUM_FRAMES: 16
  SAMPLING_RATE: 4
  INPUT_CHANNEL_NUM: [3]
DETECTION:
  ENABLE: True
  ALIGNED: True
AVA:
  FULL_TEST_ON_VAL: True
  MIN_SIZE_TRAIN: [288,]
  MIN_SIZE_TEST: 288
  CROP_ENABLED: False
  IMG_PROC_BACKEND: detectron2
  DETECTION_SCORE_THRESH: 0.7
  TRAIN_PREDICT_BOX_LISTS: []
  TEST_PREDICT_BOX_LISTS: ["ava_val_v2.1.csv"] # Only used for generating coco format json file for person detector head
  TRAIN_GT_BOX_LISTS: ["ava_train_v2.1.csv"]
  LABEL_MAP_FILE: "ava_action_list_v2.1_for_activitynet_2018.pbtxt"
  GROUNDTRUTH_FILE: "ava_val_v2.1.csv"
ViT:
  EMBED_DIM: 1024
  DEPTH: 24
  NUM_HEADS: 16
  USE_CHECKPOINT: True
  DROP_PATH_RATE: 0.2
  FPN_INDICES: [ 5, 11, 17, 23 ]
SOLVER:
  BASE_LR_SCALE_NUM_SHARDS: True
  # default 0.000025 for BATCH=16 0.00001 for BATCH=8
  BASE_LR: 0.00001
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 5, 8]
  LRS: [1, 0.1, 0.01]
  LR_SCALE: 8.0
  MAX_EPOCH: 12
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  WARMUP_EPOCHS: 2.0
  WARMUP_START_LR: 0.0000025
  OPTIMIZING_METHOD: adamw
MODEL:
  NUM_CLASSES: 80
  ARCH: vit
  MODEL_NAME: EVAD
  LOSS_FUNC: bce
  ROI_BOX_HEAD:
    POOLER_TYPE: "ROIAlignV2"
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
  SparseRCNN:
    ACTION_WEIGHT: 6.0
  KTP:
    KEEP_RATES: [ 1, 1, 1, 1, 1, 1, 0.7, 1, 1, 1, 1, 1, 0.7, 1, 1, 1, 1, 1, 0.7, 1, 1, 1, 1, 1 ]
    ENHANCED_WEIGHT: 1
  CRD:
    ROI_EXTENSION: (0.4, 0.2)
    EMBED_DIM: 512
    DEPTH: 12
    NUM_HEADS: 8
    DROP_PATH_RATE: 0.1
TEST:
  ENABLE: False
  DATASET: ava
  BATCH_SIZE: 4
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
LOG_MODEL_INFO: False
OUTPUT_DIR: "path/to/output/ava_evad_vitl_kpr0.7"
LOG_PERIOD: 50
TENSORBOARD:
  ENABLE: True
